[build]
  command = """
    pip install -r requirements.txt &&
    mkdir -p public &&
    cp -r * public/ &&
    touch public/runtime.txt &&
    echo "python-3.8.12" > public/runtime.txt &&
    touch public/Procfile &&
    echo "web: streamlit run app.py --server.port $PORT" > public/Procfile
  """
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/streamlit"
  status = 200
  force = true
